services:
  symfony:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/symfony
    depends_on:
      - mysql
      - redis

# PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
