article_index:
    path: /api/articles
    controller: App\Controller\ArticleController::index
    methods: [GET]

article_export:
    path: /api/articles/export
    controller: App\Controller\ArticleController::export
    methods: [GET]